[package]
name = "caps_wasm"
version = "0.1.0"
edition = "2024_07"

[cairo]
enable-gas = false

[dependencies]
cairo_execute = "2.11.4"


[[target.executable]]
name = "caps_wasm"
function = "caps_wasm::simulate::main"