[package]
name = "wasm"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dev-dependencies]
cairo_test = "2.11.4"


 [cairo]
enable-gas = false

[executable]
function = "wasm::main::main"

[dependencies]
cairo_execute = ">=2.11.4"