"""Generate contract geometry and distance tables from rules/boards.json."""
import json, pathlib, sys, re
from collections import deque
root = pathlib.Path(__file__).resolve().parents[1]
boards = json.loads((root/'rules/boards.json').read_text())
graphs = {}
lines = ['// Generated by scripts/generate-boards.py; edit rules/boards.json.', 'use caps::models::game::Vec2;']
assert len({b['id'] for b in boards}) == len(boards), 'Duplicate layout ID'
lines += ['pub fn dimensions(layout: u8) -> (u8, u8) {', '    match layout {']
for b in boards:
    assert 0 < b['width'] <= 15 and 0 < b['height'] <= 15
    lines.append(f"        {b['id']} => ({b['width']}, {b['height']}),")
lines += ['        _ => (0, 0),', '    }', '}']
for slot in [1,2]:
    lines += [f'pub fn p{slot}_base(layout: u8) -> Vec2 {{', '    match layout {']
    for b in boards:
        x,y=b[f'p{slot}Deploy']; lines.append(f"        {b['id']} => Vec2 {{ x: {x}, y: {y} }},")
    lines += ['        _ => Vec2 { x: 255, y: 255 },', '    }', '}']
lines += ['pub fn energy_space(layout: u8, pos: Vec2) -> bool {', '    match layout {']
for b in boards:
    expr=' || '.join(f'(pos.x == {x} && pos.y == {y})' for x,y in b['energySpaces']) or 'false'
    lines.append(f"        {b['id']} => {expr},")
lines += ['        _ => false,', '    }', '}', 'pub fn distances(layout: u8, source: u8) -> Array<u8> {', '    match (layout, source) {']
for board in boards:
    width,height=board['width'],board['height']
    graph = {p:set(n) for p,n in graphs.get(board.get('extends'),{}).items()}
    for path in board['paths']:
        for p in path:
            x,y=p
            assert isinstance(x,int) and isinstance(y,int) and 0<=x<width and 0<=y<height
            graph.setdefault(tuple(p),set())
        for a,b in zip(path,path[1:]):
            a,b=tuple(a),tuple(b)
            assert a!=b
            graph[a].add(b); graph[b].add(a)
    assert all(tuple(p) in graph for p in [board['p1Deploy'],board['p2Deploy'],*board['energySpaces']]), 'Special space not on path'
    graphs[board['id']]=graph
    for source in sorted(graph,key=lambda p:p[1]*width+p[0]):
        dist={source:0}; queue=deque([source])
        while queue:
            p=queue.popleft()
            for n in graph[p]:
                if n not in dist: dist[n]=dist[p]+1; queue.append(n)
        assert len(dist)==len(graph), 'Disconnected board'
        values=[dist.get((x,y),255) for y in range(height) for x in range(width)]
        lines.append(f"        ({board['id']}, {source[1]*width+source[0]}) => array![{', '.join(map(str,values))}],")
    lines.append(f"        ({board['id']}, _) => array![{', '.join(['255']*(width*height))}],")
lines+=['        _ => array![],', '    }', '}']
path=root/'contracts/src/logic/board_data.cairo'
content='\n'.join(lines)+'\n'
if '--check' in sys.argv:
    canonical = lambda s: re.sub(r',(?=[\]\)])', '', re.sub(r'\s+', '', s))
    assert canonical(path.read_text())==canonical(content), 'Board tables are stale; run scripts/generate-boards.py'
else: path.write_text(content)
