"""Generate contract distance tables from explicit paths. Run with --check in validation."""
import json, pathlib, sys, re
from collections import deque
root = pathlib.Path(__file__).resolve().parents[1]
boards = json.loads((root/'rules/boards.json').read_text())
graphs = {}
lines = ['// Generated by scripts/generate-boards.py; edit rules/boards.json.', 'pub fn distances(layout: u8, source: u8) -> Array<u8> {', '    match (layout, source) {']
for board in boards:
    graph = {p:set(n) for p,n in graphs.get(board.get('extends'),{}).items()}
    for path in board['paths']:
        for a,b in zip(path,path[1:]):
            a,b=tuple(a),tuple(b)
            assert a!=b and all(0<=v<5 for p in (a,b) for v in p)
            graph.setdefault(a,set()).add(b); graph.setdefault(b,set()).add(a)
    graphs[board['id']]=graph
    for source in sorted(graph,key=lambda p:p[1]*5+p[0]):
        dist={source:0}; queue=deque([source])
        while queue:
            p=queue.popleft()
            for n in graph[p]:
                if n not in dist: dist[n]=dist[p]+1; queue.append(n)
        values=[dist.get((x,y),255) for y in range(5) for x in range(5)]
        lines.append(f"        ({board['id']}, {source[1]*5+source[0]}) => array![{', '.join(map(str,values))}],")
lines+=['        _ => array![255; 25],', '    }', '}']
# Cairo array! does not support repeated-element syntax.
lines[-3]='        _ => array!['+', '.join(['255']*25)+'],'
path=root/'contracts/src/logic/board_data.cairo'
content='\n'.join(lines)+'\n'
if '--check' in sys.argv:
    canonical = lambda s: re.sub(r',(?=[\]\)])', '', re.sub(r'\s+', '', s))
    assert canonical(path.read_text())==canonical(content), 'Board tables are stale; run scripts/generate-boards.py'
else: path.write_text(content)
